version: '3'

services:
    sml:
        build:
            context: .
            dockerfile: Dockerfile
        image: jwansek/subredditmodactionslog
        network_mode: "host"
    cron:
        build:
            context: ./onceaday
            dockerfile: Dockerfile
        network_mode: host
        volumes:
            - ./onceaday/onceaday.log:/app/onceaday/onceaday.log

