version: '3'

services:
    sml:
        build:
            context: .
            dockerfile: Dockerfile
        image: jwansek/subredditmodactionslog
        network_mode: "host"
    cron:
        build:
            context: .
            dockerfile: OADDockerfile
        network_mode: host

